### ISSUE TITLE
US 06.02.01

### ISSUE THREAD

**Issue by dfloren** [CMPUT301W21T04/Crowder#11]
As an experimenter, I want to add Geo-location to experimental trials that need it so that location data is available for the experiment.

**Comment by rsandz** [comment]
**Clarifications:**
1) Is the geo-location map global or just Edmonton?

It's global, you'll use google maps or openstreet maps

https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=1661773

**Comment by dfloren** [comment]
Clarification:
Do we need to display QR codes in the following instances:
1. When generating a new QR code, before printing
2. When viewing already existing QR codes

**Comment by rsandz** [comment]
## Tasks - Ryan
- [x] Create Location class
- [ ] Create GPS permissions request workflow [Currently done on starting app.]
- [x] Retrieve current location using the location API
- [x] Create an adapter for our location class and the location API class. 
- [x] Create handler class to wrap ~DB and~ location API functionality

> Note that we have our own location class since the location class in API does not have default constructor.
> So it is not compatible with firebase!

## Testing
- [x] Create unit tests for location handler.
